// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ynkkxtwagizzzckfcvjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlua2t4dHdhZ2l6enpja2ZjdmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MTA2NTEsImV4cCI6MjA3ODM4NjY1MX0.rb0I34xgTbwLT1QWb_oFKqA1f5mhaqGL0wRSLCf-d4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);